<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>ZEBRA</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- <link rel="shortcut icon" href="Magzter-QR-code-Gold.ico" type="image/x-icon"> -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat|Ubuntu" rel="stylesheet"> <!-- Google Fonts -->


  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="index.css"> <!-- CSS Stylesheets -->


  <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script> <!-- Font Awesome -->


  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> <!-- Bootstrap Scripts -->
</head>

<body>

  <section class="colored-section" id="title">

    <div class="container-fluid">


      <nav class="navbar navbar-expand-lg navbar-dark">

        <a class="navbar-brand" href="">ZEBRA</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">

          <ul class="navbar-nav ml-auto">

            <li class="nav-item">
              <a class="nav-link " href="login.php">LOGOUT</a></a>
            </li>

          </ul>

        </div>
      </nav>




      <div class="row">

        <div class="col-lg-6">

          <h1 class="big-heading">Future ready attendence system</h1>
          <br><br>
          <form  action="qrcode.php" method="post" target="_blank">
              <button type="submit"  class="btn btn-dark  btn-lg generate-code"><i class=" fas fa-qrcode fa-1x"></i> GENERATE QR CODE </button><br><br>
          </form>
          <form  action="Zebra-App.apk" method="post" >
              <button type="submit"  class="btn btn-dark  btn-lg generate-code"><i class=" fas fa-download fa-1x"></i> DOWNLOAD ZEBRA APP </button>
          </form>
        </div>

        <!-- <div class="col-lg-6">
          <img class="title-image" src="titleimg.jpg" alt="title image">
        </div> -->

      </div>

    </div>

  </section>




  <section class="white-section" id="features">

    <div class="container-fluid">

      <div class="row">
        <div class="feature-box col-lg-4">
          <i class="icon fas fa-qrcode fa-5x"></i>
          <h3 class="feature-title">Fast generation</h3>
          <p> rapid QR code generation </p>
        </div>

        <div class="feature-box col-lg-4">
          <i class="icon fas fa-mobile-alt fa-5x"></i>
          <h3 class="feature-title">Mobile responsive Site</h3>
          <p>Compatible with all types of devices</p>
        </div>

        <div class="feature-box col-lg-4">
          <i class="icon fas fa-laptop fa-5x"></i>
          <h3 class="feature-title">Easy To Use</h3>
          <p>Faculty friendly </p>
        </div>
      </div>


    </div>
  </section>


  <section class="colored-section" id="pricing">

    <h2 class="section-heading">WHY QR CODE BASED ATTENDENCE SYSTEM</h2>
    <p> <em>Overcomming Stereotypical ways of taking Attendence.</em></p>

    <ul class="listul">
      <li>The website is basically created for the Teachers/Faculty who can register and login to the website and can easily generate the QR code for any particular lecture</li><br>
      <li>The other part of the project will be the mobile application in which a student can register or login by giving their details like class, name, roll number and on the basis of that they can mark their respective attendance by scanning the QR code which was generated by the teacher/faculty</li><br>
      <li> we have also added the functionality where the application checks whether the QR code being scanned is the same QR code provided by the teaching faculty and thereby notifies the student whether or not their attendance has been marked or not.</li><br>
    </ul>

  </section>



  <footer class="white-section" id="footer">
    <div class="container-fluid">

      <p><b><h5><u>QR code minor project team</u></h5></b></p>
      <p><b>19 - NITISH KUMAR</b></p>
      <p><b>52 - NIKHIL NAIR</b></p>
      <p><b>55 - DARSHAN PANDHARKAR</b></p>
      <p><b>Mentored By - DR SACHIN BHOITE</b></p>
    </div>
  </footer>


</body>

</html>
